// This file is auto-generated by scripts/reupload-all-assets.ts
// DO NOT EDIT MANUALLY

export const demoImageMapping: Record<string, string> = {
  "/demo-1.png": "demo-images/demo-1",
  "/demo-2.png": "demo-images/demo-2",
  "/demo-3.png": "demo-images/demo-3",
  "/demo-4.png": "demo-images/demo-4",
  "/demo-5.png": "demo-images/demo-5",
  "/demo-6.png": "demo-images/demo-6",
  "/demo-7.png": "demo-images/demo-7",
  "/demo-8.png": "demo-images/demo-8",
  "/demo-9.png": "demo-images/demo-9",
  "/demo-10.png": "demo-images/demo-10",
  "/demo-11.png": "demo-images/demo-11",
  "/demo-12.png": "demo-images/demo-12",
  "/demo-13.png": "demo-images/demo-13",
  "/demo-14.png": "demo-images/demo-14",
  "/demo-15.png": "demo-images/demo-15"
};

export const demoImagePublicIds: string[] = [
  "demo-images/demo-1",
  "demo-images/demo-2",
  "demo-images/demo-3",
  "demo-images/demo-4",
  "demo-images/demo-5",
  "demo-images/demo-6",
  "demo-images/demo-7",
  "demo-images/demo-8",
  "demo-images/demo-9",
  "demo-images/demo-10",
  "demo-images/demo-11",
  "demo-images/demo-12",
  "demo-images/demo-13",
  "demo-images/demo-14",
  "demo-images/demo-15",
];
